#!/bin/bash

set -e

source /RELEASE

sed -i "/DOWNLOAD_URL/d;/CI_JOB_TOKEN/d;" /RELEASE

echo "Downloading package as artifact - ${DOWNLOAD_URL}"
wget --quiet --content-disposition ${DOWNLOAD_URL} -O /gitea

results=$?
if [ ${results} -ne 0 ]; then
    >&2 echo "There was an error downloading ${DOWNLOAD_URL}. Please check the output for more information"
    exit ${results}
fi